---
title: "STT-1900"
---


Voici les différentes informations pour le cours STT-1900 de l'automne 2025. Veuillez noter que ce site est complémentaire au site de cours sur monPortail. Les informations de monPortail sont celles qui prévalent.

# Plan de cours
-   [Plan de cours](../STT-1900/plan_STT-1900.pdf){target="_blank"} <!-- target blank ouvre un nouvel onglet -->

Voici les différentes applications Shiny pour le cours STT-1900

# Applications SHINY


-   [Module 3 - TCL introduction, diapo # 26](https://jmiron.shinyapps.io/introTCL/){target="_blank"}
-   [Module 6 - Moyenne échantillonnale, loi inconnue, diapos # 15 et 17](https://jmiron.shinyapps.io/MoyEchExp/){target="_blank"}
-   [Module 6 - Moyenne échantillonnale, loi normale, diapos # 10 et 20-21 ](https://jmiron.shinyapps.io/MoyEchNorm/){target="_blank"}
-   [Module 6 - Loi du khi-carré, diapo # 25](https://jmiron.shinyapps.io/KhiCarre/){target="_blank"}
-   [Module 6 - Exemple, khi-carré, diap # 29](https://jmiron.shinyapps.io/ExempleKhiCarre/){target="_blank"}
-   [Module 6 - Standardisation par S ou Sigma, diapo # 31](https://jmiron.shinyapps.io/StdSvSigma/){target="_blank"}
-   [Module 6 - Loi de Student, diapo # 35](https://jmiron.shinyapps.io/Student/){target="_blank"}
-   [Module 7 - Introduction aux intervalles de confiance, diapo # 3](https://jmiron.shinyapps.io/ICintro/){target="_blank"}
-   [Module 7 - Intervalle de confiance, variance connue, diapo # 13](https://jmiron.shinyapps.io/ICVarConnue/){target="_blank"}
-   [Module 7 - Vrais ou faux, intervalle de confiance, diapo # 15](https://jmiron.shinyapps.io/VFVarConnue/){target="_blank"}
-   [Module 8.1 - Introduction aux tests, diapo # 7](https://jmiron.shinyapps.io/IntroTest/){target="_blank"}
-   [Module 8.1 - Illustration de la valeur-p, diapo # 21](https://jmiron.shinyapps.io/valeurP/){target="_blank"}
-   [Module 8.1 - Exemple des dés, diapo # 23](https://jmiron.shinyapps.io/valeurP/){target="_blank"}
-   [Module 9 - Illustration des paramètres de l'ANOVA, diapo # 16 et 20](https://jmiron.shinyapps.io/ANOVApara/){target="_blank"}
-   [Module 9 - Illustration de la décomposition de la variabilité de l'ANOVA, diapo # 24](https://jmiron.shinyapps.io/ANOVA_SS/){target="_blank"}
-   [Module 10 - Introduction du modèle de régression linéaire simple, diapo # 10](https://jmiron.shinyapps.io/ModeleIntro/){target="_blank"}
-   [Module 10 - Corrélation en régression linéaire simple, diapo # 55](https://jmiron.shinyapps.io/RegLinCorr/){target="_blank"}

Merci de relever les erreurs que vous pourriez trouver dans les applications Shiny et de communiquer avec moi par courriel à [julien.miron@mat.ulaval.ca](mailto:julien.miron@mat.ulaval.ca).

